import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inconsolata = Inconsolata({
  variable: "--font-inconsolata-sans",
  subsets: ["latin"],
  weight: "400",
});

const inconsolataSemiBold = localFont({
  src: "../../public/Inconsolata-SemiBold.ttf",
});

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inconsolataSemiBold.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
